
stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: node:latest
  before_script:
  - npm install -g vite
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

deploy:
  stage: deploy
  only:
    - main
  image: google/cloud-sdk:alpine
  environment: Production
  script:
    - echo $SERVICE_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
    - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
    - gcloud app deploy app.yaml --quiet --project $PROJECT_ID --no-cache
    - gcloud app deploy dispatch.yaml --project $PROJECT_ID
  after_script:
    - rm /tmp/$CI_PIPELINE_ID.json