runtime: nodejs20
service: frontend
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /
    static_dir: dist